### ISSUE TITLE
Unable to type G̃ / g̃ (only available as a combining diacritical marks)

### ISSUE THREAD

**Issue by bidaian** [fcitx/fcitx5#1005]
**Describe the bug**
The [guarani alphabet](https://en.wikipedia.org/wiki/Guarani_alphabet) uses a [combination of the letter g and a tilde](https://en.wikipedia.org/wiki/G%CC%83): G̃ / g̃

I cannot type it though, fcitx5 outputs ~g instead of g̃. Note that if I type n + tilde I do get ñ as expected.

**To Reproduce**
With a keyboard layout that includes the dead tilde, type tilde + n (to get ñ) and then tilde + g.

**Expected behavior**
I expect the letters G̃ / g̃ to appear

**Desktop (please complete the following information):**
 - Desktop: Gnome (Debian 12) also tested with Xfce4 (Debian 12)
 - Display server type: X11
 - The output of fcitx5-diagnose if possible: attached

**Additional context**
G̃ / g̃ are not precomposed characters, the only way to get them is by using combining diacritical marks: U+0047 U+0303 /	U+0067 U+0303.
[info.txt](https://github.com/fcitx/fcitx5/files/14830185/info.txt)

**Comment by wengxt** [comment]
@bidaian fcitx5-diagnose shows you set us layout in fcitx config. Can you setup layout with fcitx instead?

**Comment by wengxt** [comment]
Ok, so I tried with the es-deadtilde layout from your xkb setting, indeed AltGr+4 and G doesn't produce G̃. After taking a closer look on the relevant config file, it seems to be an expected behavior to me. 

First of all, you're using a layout that produce "deadtilde", it doesn't produce U+0303. By it's name, it's "dead", which doesn't produce any text on its own.

Usually, dead key are used with XCompose, then if we look into XCompose that will be loaded by your locale: en_US.UTF-8

/usr/share/X11/locale/en_US.UTF-8/Compose , it doesn't contain a sequence that contains a "G".

The only line that I found that seems relevant to your description is this line

```
<dead_tilde> <nobreakspace>          : "̃"    U0303 # COMBINING TILDE
```

Which requires you to press a key that produce nobreakspace. Your es-deadtilde won't do it (small trick: a tool in fcitx5-configtool allow you to visual like the layout `kbd-layout-viewer5 -l es -v deadtilde`). So far I notice that xkb option allow you to override space behavior, e.g. I set nbsp:level3

So now I could type g̃ with g AltGr+4 AltGr+space.

If you want to type <dead_tllde> <g> to type g̃ , then you should define your own ~/.XCompose file.

Save following content to ~/.XCompose and restart fcitx5 should allow you to use <AltGr+4> <g/G> to type g̃/G̃
```
include "%L"
<dead_tilde> <g> : "g̃"
<dead_tilde> <G> : "G̃"
```
