### ISSUE TITLE
Control + Key starts repeating Key

### ISSUE THREAD

**Issue by edarzh** [fcitx/fcitx5#1028]
**Describe the bug**
When you press Control (1 or 2 times) and then press Key the Key (a-z) gets repeated.

**To Reproduce**
1. Open Alacritty (or Foot, or Vivaldi)
2. Try to type Control (1, 2 times) and any Key (a-z) quickly

**Expected behavior**
Insert Control + Key

**Desktop (please complete the following information):**
 - Desktop: Hyprland
 - Display server type: Wayland

**Additional context**

Occurs with:
- Keyboard - English (US) - English (Colemak)
- Keyboard - Russian

Doesn't occur with:
- Keyboard - English (US)
- Mozc

[fcitx5-diagnose output](https://github.com/fcitx/fcitx5/files/15101385/diagnose.txt)

https://github.com/fcitx/fcitx5/assets/90803167/a718ec0d-5699-4454-9029-c60ee9e097b8

https://github.com/fcitx/fcitx5/assets/90803167/71d9ca08-72eb-4c60-882c-0e19ea8b96b9

**Comment by wengxt** [comment]
One of the reason that I'd like to blame the silly design of wayland im....

So basically if a "key release" is handled by input method, but not the key press, client side repetition will be triggered...

**Comment by wengxt** [comment]
basically the sequence of even is like:

Ctrl pressed
L pressed
Ctrl released
L released, but filtered by fcitx, due to current implementation, so app doesn't see L released and start repetition.

This is quite silly since whether an key event is filtered by input method or not should be fully controlled by input method, and the wayland's input method keyboard grab model totally break the point of this..

anyway, can you test with master and see if the issue is gone?

**Comment by edarzh** [comment]
Tested with master. Seems to be working 👍

**Comment by llyyr** [comment]
I couldn't trigger this with 5.1.9 but it seems to happen for me still on 5.1.10. It's not consistent and I don't yet know the steps to reproduce it consistently. How do I go about collecting useful debug logs?
