### ISSUE TITLE
how to use fcitx5 with src/waylandinputwindow.cpp?

### ISSUE THREAD

**Issue by cp9ev** [fcitx/fcitx5#113]
i am using fcitx5 in wayland and native applications but it just running at  xcb . and there is a inputwindow,like candidate window maybe, it have a wrong positon.  
so i try fix that problem, i fount this fcitx5 always use function in the xcbinputwindow.cpp, but there truly have a waylandinputwindows.cpp, maybe i miss some enviroment variables to make fcitx5 runing in native wayland ? 
or how can i get these wayland*.cpp files runing?
sr fo my bad english.

**Comment by wengxt** [comment]
It makes no sense to use wayland to draw window because there's no way you can move the wayland window based on an absolution coordinate unless input-method wayland protocol is used (which is not really supported anywhere. I noticed kwin recently support it but I never tried it so you need to use wayland im module to test it.).

In a word, don't expect it works unless you're using gnome + https://extensions.gnome.org/extension/261/kimpanel/.

https://www.csslayer.info/wordpress/fcitx-dev/gaps-between-wayland-and-fcitx-or-all-input-methods/

**Comment by AndreaOrru** [comment]
Doesn't Sway support input-method now?

https://github.com/swaywm/sway/pull/4740

**Comment by wengxt** [comment]
@AndreaOrru first, your client need to support text input v3, which is only supported by gtk nowadays. Then, you'll need to make gtk use it. Then sway need to implement, which it doesn't get_input_popup_surface. So basically no ui.
