### ISSUE TITLE
hello, looking for a tutorial of how to setup chinese input

### ISSUE THREAD

**Issue by arthureroberer** [fcitx/fcitx5#145]
if already possible of course
Im invested in fcitx5 because fcitx doesnt work well in sway/wayland

**Comment by wengxt** [comment]
there's nothing too special about fcitx5 comparing to fcitx. 

https://fcitx-im.org/wiki/Configure_(Other) still applies, but you'll need to first find a place to set the env var. (e.g. ~/.bashrc becasue xprofile certainly won't be loaded for wayland).

Also, input method doesn't work well under sway is not fcitx's fault. Compositor, application need to adopt the mechanism otherwise it would have some flaw. Fcitx is already doing all it best at this time 

Currently, only GNOME/Wayland is the only wayland environment that is closest to a usable state.

**Comment by wengxt** [comment]
For configuring fcitx, fcitx5-config-qt may be used (https://github.com/fcitx/fcitx5-configtool).
