### ISSUE TITLE
[Feature]svg support in the classic UI

### ISSUE THREAD

**Issue by marguerite** [fcitx/fcitx5#2]
Hi, this is the long living feature request...it's year 2017 with so many HDPI screens existing, we really shouldn't use the 9 parts theming engine any more:-(

**Comment by wengxt** [comment]
the 9 part theme engine has nothing to do with the svg. Just to remind you, Plasma use 9 part and svg together. The only reason that I never try to add svg support is that I'm not a big fan of librsvg.

**Comment by marguerite** [comment]
Well, if so, what about github.com/svgpp/svgpp?

**Comment by wengxt** [comment]
well obviously no.. it doesn't render anything by itself.

Ok, last time I checked the problem is the license, but I was actually confused by the name of license. The license is actually called "GNU Library General Public License", which is actually a old version of lgpl (lesser vs "library", they changed name..)... 

So probably I could add svg support later.

**Comment by marguerite** [comment]
Well...I was just about to say then you can use any xml parser you like...never mind 

I will open an issue to see if the license problem can be solved.

**Comment by marguerite** [comment]
They changed the license to "Boost

**Comment by wengxt** [comment]
Ah, actually I mean librsvg. To use libsvgpp, there seems to be more work comparing with librsvg.

**Comment by wengxt** [comment]
Actually this is just implemented.
