### ISSUE TITLE
ASK: Does fcitx5 support wine like wechat?

### ISSUE THREAD

**Issue by zyf0330** [fcitx/fcitx5#262]
I try fcitx5 and it works in chrome or telegram, but it doesn't work in wine wechat.

**Comment by wengxt** [comment]
It's likely your problem is either with configuration, or wine itself if you didn't install the offical wine.

1. check if xterm works. If it works, then XIM related configuration is OK. Otherwise please exam XMODIFIERS and if locale-gen is used properly.
2. check if wine's notepad works. If not, then your wine is probably not OK. I know some patched wine (e.g. deepin-wine) doesn't work with input method.

I tried wine-wechat from archlinux cn + wine from offical repo and it works.

**Comment by zyf0330** [comment]
When using fcitx, input Chinese in xterm is normal. But using fcitx5, it doesn't.

**Comment by wengxt** [comment]
can you provide the output of fcitx5-diagnose

**Comment by zyf0330** [comment]
It seems that Ubuntu has no fcitx5-diagnose.

**Comment by zyf0330** [comment]
After upgrade Ubuntu to v20.10 and update fcitx5 related packages, this problem disappears.
