### ISSUE TITLE
Autostart fails on KDE & X11

### ISSUE THREAD

**Issue by trmdi** [fcitx/fcitx5#387]
For some reasons fcitx can't not start automatically on KDE X11. It appears on the system tray for about 2s then it quits.

- Manually clicking on the autostart .desktop file still works.
- Autostart works on wayland too.

Git version on Tumbleweed.

**Comment by trmdi** [comment]
I've found that if you run the second instance of fcitx5, it will crash.

**Comment by wengxt** [comment]
The error you show here just seems to be there's some other input method running. I think it's quite expected here. Can you figure out which the other input method is current running?

Also doesn't opensuse have its own way of start input method?

**Comment by trmdi** [comment]
No, there are only one fcitx5 here.
As I talked above, when you run the 2nd instance of fcitx5 while the is another running, both instances will quit. I think only one instance should quit, not both.

**Comment by wengxt** [comment]
So you're saying, if you start one fcitx5, when trying to start another one will crash(or, not really crash, just make it quit) the old running fcitx5?

Can you run both in separate terminal with `--verbose=default=5` and paste the log here?

**Comment by wengxt** [comment]
@wengxt nvm I can reproduce it here. Will take a look

**Comment by wengxt** [comment]
> No, there is only one fcitx5 here. As I talked above, when you run the 2nd instance of fcitx5 while the is another running, both instances will quit. I think only one instance should quit, not both.

Sorry I misunderstood the behavior here, I don't have the same problem. Still need some information from your side.

**Comment by trmdi** [comment]
Ok, here is the log

[fcitx5-instance1.log](https://github.com/fcitx/fcitx5/files/7623085/fcitx5-instance1.log)
[fcitx5-instance2.log](https://github.com/fcitx/fcitx5/files/7623086/fcitx5-instance2.log)

**Comment by wengxt** [comment]
Are you sure instance 1 quits? The log doesn't show anything about whether it quits.

**Comment by trmdi** [comment]
Yes, I recheck with `pgrep fcitx` which returns nothing.

**Comment by wengxt** [comment]
@trmdi can you try to use gdb attach on instance 1? (maybe in a tty, or from a input method disabled terminal, otherwise it would block, you can start a xterm with `XMODIFIERS=@im=none xterm` and run `XMODIFIERS=@im=fcitx gdb fcitx5` with in the xterm )

Also when you say you run git version on tumbleweed, do you mean that you compile fcitx yourself?

**Comment by trmdi** [comment]
I've just tried your latest commits, the issue is solved now.

**Comment by trmdi** [comment]
However there is a minor issue when fcitx is launched through auto run, the icon looks weird:
![image](https://user-images.githubusercontent.com/11857205/144528366-2272be4b-d65e-4c1a-b78e-ceed72acc47e.png)

If I run it manually from the App launcher or the terminal, it looks ok.
![image](https://user-images.githubusercontent.com/11857205/144528475-13ecffb7-d7ff-46f7-815a-20dbcea70324.png)

**Comment by wengxt** [comment]
I have no idea about why is that, it just send the icon name over the dbus.

But I guess at this point it's not possible to investigate further on the original issue. What I tried is to fix the singleton detection with libdbus, but even that, it should not quit existing fcitx, especially when there's no log indicate that it is a proper quit.

One of my guess is that ibusfrontend code about kill other ibus somehow send to another fcitx, but there's some code prevent this. So I don't have another theory on the root cause.

Close for now.
