### ISSUE TITLE
Does not work on KDE+Wayland

### ISSUE THREAD

**Issue by hardboiled65** [fcitx/fcitx5#416]
I found an example using wayland's text-input-v3-unstable protocol.
https://aznote.jakou.com/prog/wayland/p02_textinput.html

I downloaded the full source code and modified little for stable xdg-shell protocol.
https://github.com/hardboiled65/WaylandClient-text-input

This program simply activates an input method(for me, Shift+Space key combination) and get inputs from user and print to console.
It works with fcitx5 on gnome-shell even the author said only tested with ibus.

But it does not work on KDE plasma with Wayland, while fcitx5 is working well with Qt applications.

I tested it under Arch Linux on VirtualBox, host machine is Manjaro Linux. fcitx5 version I used is 5.0.11

I have only Mozc input method but I think it's not important. Is this a KDE's problem? Both gnome-shell and plasma has `zwp_text_input_manager_v3` protocol. In gnome-shell, also `gtk_text_input_manager` protocol exists but as I known fcitx5 not implement this protocol so this is not a problem.

Sorry for my poor english and I can't speak Chinese.

**Comment by wengxt** [comment]
Ah, as for this, you need to configure kwin to start fcitx. What you need to do is to write following config into ~/.config/kwinrc , otherwise it's not authorized to use zwp_input_method_v1 in kwin.

```
[Wayland]
InputMethod=/usr/share/applications/org.fcitx.Fcitx5.desktop
```

While this is currently possible to enable it, I have found quite a few issues in both fcitx / kwin's implementation when I'm testing it recently and I'm trying to fix it so we can have it ready by the next plasma release.

https://invent.kde.org/plasma/kwin/-/merge_requests?scope=all&state=merged&author_username=xuetianweng
https://invent.kde.org/plasma/kwayland-server/-/merge_requests?scope=all&state=merged&author_username=xuetianweng

If you really want to test it, I suggest you to run kwin master / fcitx5 master.

Also, although it is possible to use kwin's text-input-v3/zwp_input_method_v1 + fcitx5, I'd say the design of this protocol is quite flawed. To get better experience, I suggest using fcitx5-gtk/fcitx5-qt to for fcitx's dbus interface if possible for now.

**Comment by hardboiled65** [comment]
Thank you for your response. Even I tried with kwinrc, it does not work. I'll test more various environments.

And I'm not using neither GTK nor Qt for my example but pure wayland-client. Applications built in Qt are works well with fcitx5 already since I'm using fcitx5-qt.

**Comment by wengxt** [comment]
Can you paste your kwinrc? Also you need to logout and login to make it work.

You might want to disable fcitx5's xdg autostart. Otherwise it might conflict with the one that started by kwin.
Once it succeeds, following command should show:

```
dbus-send --print-reply=literal --dest=org.fcitx.Fcitx5 /controller org.fcitx.Fcitx.Controller1.DebugInfo
```

It should show
```
   Group [x11::1] has 0 InputContext(s)
Group [wayland:] has 1 InputContext(s)
  IC [46b3b950f95a476e8097e8af673f7189] program: frontend:wayland cap:d0052 focus:1
Input Context without group
```

Looking for the line "frontend:wayland", if it shows up this line then you're good to go.

Also, due to a bug in kwin 5.23 (Fix: https://invent.kde.org/plasma/kwin/-/merge_requests/1790), modifier key doesn't work. Which means you can't use "ctrl"+space to change input method. You may try to click the tray icon to test it.

**Comment by hardboiled65** [comment]
```
[$Version]
update_info=kwin.upd:replace-scalein-with-scale,kwin.upd:port-minimizeanimation-effect-to-js,kwin.upd:port-scale-effect-to-js,kwin.upd:port-dimscreen-effect-to-js,kwin.upd:auto-bordersize,kwin.upd:animation-speed,kwin.upd:desktop-grid-click-behavior,kwin.upd:no-swap-encourage,kwin.upd:make-translucency-effect-disabled-by-default,kwin.upd:remove-flip-switch-effect,kwin.upd:remove-cover-switch-effect,kwin.upd:remove-cubeslide-effect,kwin.upd:remove-xrender-backend

[Compositing]
OpenGLIsUnsafe=false

[Desktops]
Id_1=acc6b838-5237-4f94-b139-4c67a95f3408
Number=1
Rows=1

[Wayland]
InputMethod=/usr/share/applications/org.fcitx.Fcitx5.desktop

[org.kde.kdecoration2]
ButtonsOnLeft=XAIMS
ButtonsOnRight=H
```
This is entire content of .config/kwinrc file.

I've got the next output by the command you said.
```
   Group [wayland:] has 3 InputContext(s)
  IC [61fb7cf658a64633841f9abbbab33228] program:konsole frontend:dbus cap:e001800072 focus:1
  IC [6f4ee67fd4c14c8c8fa25ba68dafc1cb] program:plasmashell frontend:dbus cap:e001800072 focus:0
  IC [f0a41a621816423f993be1983cf79248] program: frontend:wayland cap:0 focus:0
```

It works when I toggle by tray icon. But preedit text is not show. commit text was shown. Its behaviour is different from gnome-shell.

I'm using kwin version 5.23.4

**Comment by wengxt** [comment]
Yes, as I said there's a lot of different things need to be fixed..

https://invent.kde.org/plasma/kwin/-/commit/bd40db7dd1276e17c41387cc6653b7cdb7481763
