### ISSUE TITLE
Fcitx5 crashes KDE Konsole when pressing Context key

### ISSUE THREAD

**Issue by R-L-T-Y** [fcitx/fcitx5#61]
oops, press enter and it got sent.

---
Some possible infomation:
OS/DE: Arch Linux + KDE
Fcitx5 version: latest in repo, has this issue for possibly all the versions
After killing fcitx5, context key doesn't crash konsole.
Should be quiet easy to reproduce.

---
Sorry for such a messy issue, please holler if you need any more info

**Comment by wengxt** [comment]
What is a context key?.. Sorry for my ignorance.

**Comment by R-L-T-Y** [comment]
Sorry it might be more known as [the menu ≣ key  ](https://en.wikipedia.org/wiki/Menu_key)

**Comment by wengxt** [comment]
can you provide a backtrace of konsole?

you can try to do that with gdb konsole in another terminal like xterm. After crash, run "bt" in the gdb.

**Comment by R-L-T-Y** [comment]
[fcitx-coredump.log](https://github.com/fcitx/fcitx5/files/4645392/fcitx-coredump.log)
[fcitx-gdb-bt.log](https://github.com/fcitx/fcitx5/files/4645393/fcitx-gdb-bt.log)

**Comment by wengxt** [comment]
.. this looks werid, we don't call into such a function.. 

Can you try to recompile fcitx5-qt im module with debug symbol to see if we can get a more meaningful backtrace?
```
git clone git://github.com/fcitx/fcitx5-qt
cd fcitx5-qt/
mkdir build
cd build/
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug -DENABLE_QT4=Off -DBUILD_ONLY_PLUGIN=On
cmake --build .
sudo cmake --install .
```

**Comment by wengxt** [comment]
Also, may I ask if you system up to date? Especially for Qt5.

I tried to look into the relevant part carefully,  in QPlatformScreen::serialNumber() is the function before QPlatformScreen::cursor(). There might be a new virtual function introduced in QPlatformScreen and shift the vtable of QPlatformScreen by one.

If you only installed fcitx5 recently without Syu, you might using fcitx5-qt against a older Qt (5.13 I assume, because my local diff between Qt 5.13/5.14 shows a new virtual function).

Please update your system and reopen if it's not fixed.

**Comment by R-L-T-Y** [comment]
Thank you for your time, this issue is indeed fixed after manual build against machine qt5 -- the problem is, I'm using testing branch, with Qt 5.15beta. 
CC @felixonmars , fcitx5-qt is not in community-testing, and there might be issue lying.

**Comment by felixonmars** [comment]
No, qt 5.15beta is in [kde-unstable], which doesn't contain rebuilds for any other packages than kde iirc.

**Comment by R-L-T-Y** [comment]
iirc qt5 beta used to be in testing repo and is not at the time being, am sorry that I did not check before asking.
