### ISSUE TITLE
Implement SecondThirdCandWordKey

### ISSUE THREAD

**Issue by hghwng** [fcitx/fcitx5#63]
In fcitx4, the feature of `SecondThirdCandWordKey` greatly improved typing efficiency. How about implementing this feature in fcitx5?

**Comment by wengxt** [comment]
Here's the thing, I intend to avoid having such key in global space. because it looks extremely in terms of consistency because we don't have a configurable key to select "first candidate" word (commonly, it's space or enter but not for all input method).
If you need it for pinyin/table, I can add it there.

**Comment by hghwng** [comment]
@wengxt Thanks for the explanation and kudos to the commit! And I'm still curious about the design decision: why give the power of choosing candidates to individual input methods?

**Comment by wengxt** [comment]
This is one important design change in fcitx 5. Because different input method has very different characteristics, defining a global option is hard to work for all input methods. And this is one target that we try to leave input method engine to handle all the keys instead of putting the key handling in multiple addons based on filter. Latter one is quite fragile and can easily led to unexpected behavior.

For example, prev/next page was default to - = in fcitx 4. While certain input method / keyboard layout doesn't have - = at all. - = is some key that assuming you're using us-like layout. Same applies to other global shortcuts. Put the option into each input method can make input methods to handle such situation better.

**Comment by hghwng** [comment]
That makes sense. Thanks you again for the insightful comments!

**Comment by duguyipiao** [comment]
Is it possible to set `SecondThirdCandWordKey` for the `clipboard` module?
