### ISSUE TITLE
Fcitx5 draws different emoji font on different applications

### ISSUE THREAD

**Issue by Reverier-Xu** [fcitx/fcitx5#636]
**Describe the bug**

fcitx5 draws different emoji font on different applications, in konsole it draws an outline emoji without color,

![Screenshot_20221102_021551](https://user-images.githubusercontent.com/41937333/199308654-7a771bbc-0b5b-4d97-a5ac-3614823c4dae.png)

and draws a colorful emoji in Microsoft Edge.

![Screenshot_20221102_021610](https://user-images.githubusercontent.com/41937333/199308840-df5187a9-2772-480b-988d-391894f31563.png)

I have set the font in fcitx5 ui settings:

![image](https://user-images.githubusercontent.com/41937333/199309027-aebfc195-a366-469e-9c27-fd203fd68478.png)

I noticed that my edge browser is running on xwayland. it seems that all applications running on wayland could not draw a colorful emoji.

**To Reproduce**
1. Open a wayland native app and a xwayland app
2. Try to type some word that correspond an emoji in both apps

**Expected behavior**
show the same emojis

**Desktop (please complete the following information):**
 - Desktop: KDE Plasma 5.26
 - Display server type: Wayland

**Additional context**

none.

**Comment by wengxt** [comment]
the qt panel you saw is based on client side ui, for some reason it just fail to pick emoji up.

https://bugreports.qt.io/browse/QTBUG-85744 might be relevant.

you can make it use fcitx native UI as described in https://www.csslayer.info/wordpress/linux/use-plasma-5-24-to-type-in-alacritty-or-any-other-text-input-v3-client-with-fcitx-5-on-wayland/ but just make sure you avoid kwin 5.26.0 and 5.26.1 because they have some bug prevent input popup to be shown. It's fixed in 5.26.2.

**Comment by wengxt** [comment]
this page in KDE wiki has a trick to make color emoji always work in Qt, you might want to try that.

https://community.kde.org/Distributions/Packaging_Recommendations
