### ISSUE TITLE
Switching to a next group on per-window basis

### ISSUE THREAD

**Issue by amorozov** [fcitx/fcitx5#645]
Hello!

With Fcitx5 in KDE I can't get switching to another **group** working on a per-window basis. Layouts within a single group are switched on per-window basis correctly.

I'm not sure if is an issue of Fcitx5/KDE5 or just a misconfiguration of my system.

Details of my setup and problem description:

Basically, I have three layouts active:

* us(altgr-intl) for 
Latin alphabet (English and Spanish languages)
* ru(ruu) for Cyrillic alphabet (Russian and Ukrainian languages)
* pinyin for Chinese

`us` and `ru` are put into one group while `pinyin` is in another group (think of "Western and Eastern languages").

Switching between `us` and `ru` is performed with `Ctrl-Shift` while switching to/from Chinese is performed with `Win-Space`. I have completely switched off KDE builtin keyboard applet, my system-wide keyboard configuration doesn't include a hotkey for layout switching, so I rely completely on Fcitx5 to do the layout switching job.

Everything works as desired, except for one annoying thing: the Latin/Cyrillic switch is performed on per-window basis (that is, each window has its own input language activated), while switching to Chinese is performed globally, all windows are switched to Chinese altogether, which is inconvenient.

The question: is it an issue or just a local misconfiguration? Can it be fixed somehow?

My system is Manjaro/KDE5 Plasma. 
I have attached all configuration files that may be relevant to the question.
[keyboard-configs.zip](https://github.com/fcitx/fcitx5/files/9995257/keyboard-configs.zip)

**Comment by wengxt** [comment]
HI, which group is being used is a global option, that's by design, because it's basically affect the system layout even if you're not typing text.

In your case, sounds like you may want a set up like this:
1. have only one group, put En, Ru, Pinyin in that group.
2. Make use of another built-in add on called input method selector.
    Which allows you to select input method to be used for a certain input context

input method selector addon provides two styles of changing input method,
e.g.
![image](https://user-images.githubusercontent.com/259684/201483210-08baadcd-14ed-47ed-a78f-9df55dca8e63.png)
if you setup it like this, ctrl + 1 switch to the first one, ctrl + 2 to switch to the second one etc.
Or Ctrl + ' will show you a popup list like:
![image](https://user-images.githubusercontent.com/259684/201483267-5b668ddf-645e-4133-9423-b6f51448e9cc.png)

Since you want to remember different input method for different input context, you might want to focus on the option "for only current input context".

**Comment by amorozov** [comment]
Thank you for your suggestion, I will try to consider the alternative you have mentioned.
