### ISSUE TITLE
Can not switch IM if not focusing on any text input

### ISSUE THREAD

**Issue by trmdi** [fcitx/fcitx5#647]
I don't know if it also happens on other environments, but on Plasma, you can't switch between IMs if you're not focusing on any text input. Fcitx should let the user switch in any case.
There is also a bug with the checkboxes.

![fcitx5-2022-11-15_10 07 49](https://user-images.githubusercontent.com/11857205/201818799-4abd4209-be2b-4863-8c57-ce0f58cafaca.gif)

**Comment by zenfas** [comment]
not relate to the bug! I don't why icon of Unikey not unify, icon in setting and sytem tray different? Any history about this

**Comment by wengxt** [comment]
@zenfas the icon in tray is from KDE. Likely from the breeze plasma theme. The breeze icon theme doesn't update at the same time. You can file a bug to breeze icon to ask them to sync the fcitx icon from plasma theme to the icon theme.

**Comment by wengxt** [comment]
the main reason of current behavior is due to that every input context may have different state. But I think it to allow operation makes sense if we already using "mostRecentInputContext" to display the state.

**Comment by trmdi** [comment]
What happens when you choose to share the state in all applications? And will your commit work at first startup when the most recent ic = null?

**Comment by wengxt** [comment]
The setCurrentInputMethod is also updated to allow ic to be null to update the setting.

**Comment by trmdi** [comment]
> The setCurrentInputMethod is also updated to allow ic to be null to update the setting.

Just tested it. If you don't focus in any text input, e.g. minimize all windows and show the desktop, then restart fcitx, it will not work. Is this your intention?

The usecase for this wanted behavior: 
- you turn on the PC, and click on fcitx before opening any program
- or you want to remember the last IM at startup

**Comment by zenfas** [comment]
Solution set two group above difficult for linux newbie user (most of them don't know much technicals), can fcitx make it default @wengxt? Also for fcitx4, most of guildeline on internet for install unikey with fcitx is fcitx-unikey.

**Comment by trmdi** [comment]
Yeah, the method of using Group is a bit hard to use.

Now I would try to describe it again in more proper terms. I would want to:
- click on fcitx to change it's state (active/inactive) at startup when there is no window at all
- when using "Share state between all programs", fcitx remember that state and restore it at startup.

Is this idea valid?

**Comment by wengxt** [comment]
@zenfas that style is what I hate for. 

I don't know why it becomes a de-factor standard since Windows 8.

First of all, per-window input method is desired feature for at least Chinese users. We don't want open a new window and find Chinese is active. We want English always by default in new window. Certain wayland restriction prevent this, but I've always been trying to figure out a solution for it:
https://github.com/fcitx/fcitx5/issues/487
https://github.com/fcitx/fcitx5/issues/486

Under that assumption, if per-window input method is by default, the alt-tab style switching becomes pretty bad and unpredictable if you have more than 2 input method.

What is the next one after super space (under Windows 8 style context)? To me I rarely get the input method I want on windows. I commonly have to press super space multiple times to get it.

Also, another thing that I hate is that if every input method have to provide their own "English mode". This is what they do for new Chinese Pinyin under windows, but lives a inconsistency between different input method. Imagine that if there's a unikey "english only mode" what's the difference between "pinyin" English mode? do that share the same data? do they provide the similar behavior?

Also on mobile phone, I commonly got a random Chinese/English keyboard when open a new app because it remembers the last used input method.

In the meantime, I do dislike the current UI for input method list in configtool, my ideal UI for it would be a tree that displays all the groups together, but it will need more qml work if I still want easy drag and drop.
![图片](https://user-images.githubusercontent.com/259684/202068402-46c519df-6289-4998-8190-fd2cee9a93b6.png)

Feel free to implement this: 
https://github.com/fcitx/fcitx5/issues/646

Or this
https://github.com/fcitx/fcitx5-configtool/issues/61

**Comment by trmdi** [comment]
When you use Share state with All, fcitx can't change its state if there is no window opening at all. Could this be changed?

**Comment by wengxt** [comment]
> When you use Share state with All, fcitx can't change its state if `mostRecentInputContext == null`. Could this be changed?

Added some code to allow this: https://github.com/fcitx/fcitx5/commit/52d7d682b77be1dffea03f47c10286aaedecfb58
