### ISSUE TITLE
emacs crashes when fcitx5 exits

### ISSUE THREAD

**Issue by MarkoSchuetz** [fcitx/fcitx5#730]
**Describe the bug**
This might be the wrong repository to fix my problem, but I'm hoping that someone here has a workaround.

I use fcitx5 for Chinese input. I also use Plover for typing steno. When fcitx5 is running, there are sporadic misses of characters that get input through Plover. Therefore, I want to exit from fcitx5 when I type steno, but when exiting fcitx5, emacs freezes. Any suggestion on how to prevent emacs from freezing in this situation? 

**To Reproduce**
1. run fcitx5
2. run `GTK_IM_MODULE=fcitx QT_IM_MODULE=fcitx XMODIFIERS=@im=fcitx  LC_CTYPE=zh_CN.UTF-8 emacs &`
3. exit fcitx5

**Expected behavior**
I would wish that emacs remains running.

**Comment by wengxt** [comment]
Sounds like emacs is stucked within Xlib's xim. Though emacs is a gtk app, it uses XIM internally.

Use emacs with pgtk. It allows emacs to use gtk im module instead of hardcoded XIM for input method. Otherwise the issue is in Xlib and there's nothing I can really do with it.

Some information I found online about this branch of emacs:
https://batsov.com/articles/2021/12/19/building-emacs-from-source-with-pgtk/
https://mail.gnu.org/archive/html/emacs-devel/2021-12/msg01732.html
