### ISSUE TITLE
fcitx5 支援 Virtual Key Board？

### ISSUE THREAD

**Issue by GO-jack** [fcitx/fcitx5#87]
您好
想请问 fcitx5 是否支援 Virtual Key Board 或未来是否有计画支援？
谢谢

**Comment by wengxt** [comment]
不会支持 fcitx 4 的那种，只会考虑正常触摸屏的那种。

**Comment by wengxt** [comment]
leave it open for real virtual keyboard support.

**Comment by SamLukeYes** [comment]
> 不会支持 fcitx 4 的那种，只会考虑正常触摸屏的那种。

很期待这个功能 :)

**Comment by xingwozhonghua** [comment]
https://github.com/linuxmint/onboard

fcitx5后面还有什么任务可以适合新人参与那？

**Comment by wengxt** [comment]
https://docs.google.com/document/d/1x-UcMQLLDi-ksxCQgb3L9AAuXGUYepNGkPSDUm1VlXE/edit?usp=sharing

**Comment by Bob0111** [comment]
> https://docs.google.com/document/d/1x-UcMQLLDi-ksxCQgb3L9AAuXGUYepNGkPSDUm1VlXE/edit?usp=sharing

参考实现可以参考Ubuntu touch、kde plasma Mobile等Linux手机项目。这些项目已经在wayland下实现了虚拟键盘。你们可以考虑把fcitx作为一个附加模块加上去。

**Comment by wengxt** [comment]
@daipom @ashie so as for the goal for supporting virtual keyboard in fcitx, the goal is that
1. have an abstraction for describing virtual keyboard layout
2. the abstraction can be displayed in a separate process, like kimpanel

Fcitx's own UI is kinda hacky with limited functionality, due to it doesn't use a tool kit.

There's currently another project that tries to bring fcitx to android, https://github.com/rocka/fcitx5-android-poc/, but they have the same issue like you guys: there's no abstraction, so the keyboard is also hard coded.

I'm not yet decided whether the desktop input method and the virtual keyboard should be managed in the same way, because of the existence of hybrid device.

As for display the VK window, I think it's OK to not use the wayland im protocol, since the virtual keyboard is kinda a fixed position if shell support protocol to place a window on the screen edge. 

Also, as for the abstraction, I'm thinking about to separate the key label and key shape, because re-create the key widget might be an expensive operation in certain cases. That leads to what is currently in the virtual keyboard branch, though very incomplete for now.

**Comment by wengxt** [comment]
https://gitee.com/openkylin/kylin-virtual-keyboard
