### ISSUE TITLE
[Feature] Cofigurable default behavior of the notification timeout

### ISSUE THREAD

**Issue by c31io** [fcitx/fcitx5#884]
Add something like

```
if timeout == -1 then
   timeout = default_timeout
end
```

to this function

https://github.com/fcitx/fcitx5/blob/79050b338026974f6db4dc1c056ec4a04f2c722e/src/modules/notifications/notifications.cpp#L196

**Comment by wengxt** [comment]
@c31io why would you want that

**Comment by c31io** [comment]
> @c31io why would you want that

It saves me a click on the notification sometimes

**Comment by wengxt** [comment]
showTip has an action to hide it permenantly if you don't want it.

Also as for API I don't like this idea, and it will relies on the user to change the code to use it.

And, org.freedesktop.Notifications already defines -1 as a internal value, which makes it no sense to have our own logic.

expire_timeout | INT32 | The timeout time in milliseconds since the display of the notification at           which the notification should automatically close.                               If -1, the notification's expiration time is dependent on the           notification server's settings, and may vary for the type of           notification.            If 0, never expire.
-- | -- | --


If you find a specific notification being annoying, file a bug about that notification and see if we can improve it.
