### ISSUE TITLE
some request for hotkey configuration

### ISSUE THREAD

**Issue by name-snrl** [fcitx/fcitx5#898]
Hi. I'm using `fcitx5` with English, Russian and mozc input methods on `sway` and I configure the layout switching as follows:

- trigger input method with `right_control`.
- switch to mozc with `Hiragana_Katakana` key.
- switch to Russian with `super + Hiragana_Katakana`

But to enable mozc or Russian, I use the `sway` bind which calls `fcitx5-remote` to enable a specific input method. But it would be nice to use the input method selector module to do this. But there are a number of problems with it:

- You can't set a specific key for a particular input method. If you skip mapping the first method:
![image](https://github.com/fcitx/fcitx5/assets/72071763/288d7e05-5c8e-4231-b5a3-47d84a54285a)
then it will be removed after saving. Of course, you can set some unused shortcut for the first input method, but that's a bit weird.
- Also, you can't bind a single key in this module, like `Hiragana_Katakana`.

I also noticed that the _enumerate when press trigger key repeatedly_ option doesn't work if the input method trigger is bound to a single key rather than a key combination, as in my case with `right_control`.

**Comment by wengxt** [comment]
so, I think you should be able to do that with all the changes above. To set a empty key on purpose, just "long press" the button and you will see the menu.

The latter about "enumerate when press trigger key" right now is intended. Because it's designed to implement a alt+tab style (as long as you still hold "alt", tab switching does not ends). with only a single key you just can't do that.

e.g. Ctrl + Space, it's not like you press ctrl+space and release all key multiple times, it requires you to hold ctrl, then continuously press space to trigger this.

**Comment by wengxt** [comment]
if you don't need ui to do it, you can just modify the config file manually if you want to test.

**Comment by name-snrl** [comment]
> so, I think you should be able to do that with all the changes above. To set a empty key on purpose, just "long press" the button and you will see the menu.

wow, thank you for the fast response. I'll test this out next weekend and give feedback.

**Comment by name-snrl** [comment]
Sorry, it's been a lot of work. Everything works like a charm in 5.1.6
