### ISSUE TITLE
Toggle fcitx5 with native layout switcher.

### ISSUE THREAD

**Issue by mindey** [fcitx/fcitx5#913]
**Describe the bug**
When I type in European languages, I don't need IME, so, fcitx5 should be suspend-able with a key combination.
But now, fcitx5 tries to do everything, but doesn't allow temporarily suppressing itself when it is not needed, and the key combinations are limited.

This creates issues, for example:
- fcitx5 tries to leave the text that has been entered using another input method, when switching to other input method, but it is not perfect, so it wastes time needed to delete what was entered with previous method, after switching to the next input method. If I could switch into "no fcitx5" temporarily, this would not be an issue. This used to work well in fcitx, but not so in fcitx5.
- fcitx5 prevents using needed key combinations, e.g., Ctrl+Alt, but only Alt+Ctrl is available. Such lack of set-able key combinations is also inconvenient.

**To Reproduce**
Suppose there's 2 groups: Asian languages, and European languages.
1. Start typing something in Chinese (e.g., hello, would suggest  hel l o 合理咯
2. Now, try switch to another group without completing it. (Super+Space)
3. Result: garbage text "合理咯" is created, when the intended text was "hello".
Waste of time: I have to delete it, to be able to type again...

**Expected behavior**
At the step 3, after switching to other group, there would be no text that was mistakenly entered while in the previous group, unless system is sure that the suggestion will be correct.

**Desktop (please complete the following information):**
 - Desktop: XFCE4
 - Display server type: x11
 - The output of fcitx5-diagnose if possible.

**Additional context**
- Primary reason for using layout switcher by temporarily suspending fcitx5, is because it layout switcher works faster (cause it is simple), and without delays to display notifications.

**Comment by wengxt** [comment]
As for ctrl + alt and alt + ctrl, you just need to add more combinations, since order matters. This actually gives you more fine grained control on what key need to be used

![图片](https://github.com/fcitx/fcitx5/assets/259684/1168e172-6dad-4345-ac2a-1b0eb41eea76)

in your case, it seems that you can use only one group, I'm not sure why would you want to use two group.

As for your commit text is Chinese when switching input method, are you using pinyin in fcitx5-chinese-addons? or other input method?

https://github.com/fcitx/fcitx5/assets/259684/1ef7d28b-1386-41db-82cc-cc0e55f5fb37

I recorded how it works here, I think it works exactly like what you want.
