### ISSUE TITLE
Custom Theme Not Applying in Wayland Session for Flatpak Apps

### ISSUE THREAD

**Issue by yuntaz0** [fcitx/fcitx5#970]
**Describe the bug**
When running Flatpak applications under Wayland, Fcitx5 fails to apply custom themes. This issue does not occur with applications running under XWayland. Despite following a solution from a previously closed issue ([#432](https://github.com/fcitx/fcitx5/issues/432)) which suggests enabling file system access to /usr/share/ for client-side input panels, the problem persists. Adjusting the file system access through Flatseal to allow /usr/share/ does not resolve the issue.

**To Reproduce**
1. Start a Wayland session on the desktop.
2. Open any Flatpak application under native Wayland.
3. Attempt to type anything using Fcitx5.

**Expected behavior**
Fcitx5 is expected to apply the custom theme consistently across both native and Flatpak applications, ensuring a uniform user experience.

**Desktop (please complete the following information):**
 - Desktop: KDE 5.27.10
 - Display server type: Wayland
 - The output of fcitx5-diagnose if possible.

**Additional context**
Fcitx5 is installed from Fedora RPM (`fcitx5-5.1.7-1.fc39.x86_64`)

**Comment by wengxt** [comment]
So, to explain how this works:
1. You probably set GTK/QT_IM_MODULE=fcitx , this will make flatpak use fcitx im module from the flatpak runtime, just like native app.
2. When GTK/QT_IM_MODULE=fcitx, and you are using wayland, in order to place popup window correctly, the implementation use the app toolkit to render the window. If custom theme need to be used, the app itself must be able to read fcitx theme directory.
3. An alternative way, especially, you are using KDE, follow this https://fcitx-im.org/wiki/Using_Fcitx_5_on_Wayland#KDE_Plasma , unset QT_IM_MODULE and GTK_IM_MODULE, and select fcitx5 in virtual keyboard from systemsettings. This way you should be able to use native wayland input method protocol. Thus the window will be rendered by fcitx and there's no need to make flatpak app to access theme directory.

**Comment by yuntaz0** [comment]
Thanks. It turns out that `fcitx5-autostart` was starting fcitx5 before the environment variable had a chance to be unset. It has been resolve by uninstalling `fcitx5-autostart`.

**Comment by wengxt** [comment]
IIRC fcitx5-autostart has a /etc/profile.d that sets the environment variable.

**Comment by wengxt** [comment]
And you don't need the xdg autostart anyway, since if you configure it in the system settings, kwin will launch the fcitx.

**Comment by yuntaz0** [comment]
Yes, I can confirm that removing environment variable in `/etc/profile.d/fcitx5.sh` also works.
